### ISSUE TITLE
Button not working 

### ISSUE THREAD

**Issue by Debadatta** [jarmo/RAutomation#124] opened 2019-01-15 11:04 UTC
@leviwilson 
window = RAutomation::Window.new(:title => 'XXXXXXX', :adapter => :ms_uia)
window.button(:title => "Log In").click { true 

window is opened as a popup . There are two textbox for username and password . I can set the values for these. But the Login Button not working.

Error:
RAutomation::UnknownButtonException: Button {:title=>"Log In"} doesn't exist on window {:index=>0, :title=>"XXXXXXX"}!

In windows 10 it is working but windows 7 not working

**Comment by jarmo** [comment] 2019-01-31 11:36
Sorry, but it's really hard to help without having access to the application under test etc. I recommend to set a breakpoint into your code and then evaluate there. For example, retrieve all the buttons and see how many does RAutomation find and then print out their titles (now that I think of it - is it even title for button and not a value - try value instead of title!).

Closing this since this does not seem to be an issue directly with RAutomation, but is rather a problem between different Windows versions and your app. If you can provide a reproducible example then it would be possible for someone to help.

PS! Try to keep questions like these on StackOverflow instead of opening an issue here.

**Closed by jarmo** 2019-01-31 11:36 UTC
